### ISSUE TITLE
tentang ovo-payment

### ISSUE THREAD

**Issue by lintangtimur** [aalfiann/ovo-payment#1]
ini bedanya dengan yang lain apa? yang ovo api wrapper

**Comment by aalfiann** [comment]
Bedanya dengan ovo api wrapper adalah saya membuat library ini untuk enterprise yg bekerja sama dengan OVO.

jadi library ini lebih tepatnya untuk merchant.

Oleh karena itu tidak ada feature login di dalam library ini, karena cara kerja nya **Host to Host**.

**Comment by lintangtimur** [comment]
oalah, kalo yang 
`OVO HMAC Cryptography` taunya darimana ya?

**Comment by aalfiann** [comment]
Untuk build Hmac value itu sudah ada di dalam technical documentation dr OVO.
